import React from 'react'
import type { Metadata } from 'next'

interface UserLayoutProps{
    children: React.ReactNode;
}
export const metadata: Metadata = {
    title: 'This is user layout',
    description: 'Generated by create next app',
  }
const UserLayout = ({children}:UserLayoutProps) => {
  return (
    <div>{children}</div>
  )
}

export default UserLayout